name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: check out git repository
        uses: actions/checkout@v2

      - name: install node.js, npm and yarn
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: install project dependencies
        run: npm ci

      - name: run unit tests
        run: npm run test

  publish:
    runs-on: windows-latest
    needs: [test]
    if: contains(github.ref, 'refs/tags/')
    steps:
      - name: build
        run: npm run build

      - name: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
